#!/usr/bin/env node
/**
 * Automatic label generation from HTML pairs.
 * 
 * Compares original HTML (before cleanup) with cleaned HTML (after manual cleanup)
 * and automatically generates labels for each element (keep/remove).
 * 
 * Usage:
 *   npx tsx scripts/generate-labels.ts <example-id>
 * 
 * Example:
 *   npx tsx scripts/generate-labels.ts cnet-galaxy-chip
 * 
 * This will look for:
 *   - training-data/raw/cnet-galaxy-chip-original.html
 *   - training-data/raw/cnet-galaxy-chip-cleaned.html
 * 
 * And generate:
 *   - training-data/labeled-examples.json (or append to existing)
 */

import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

import { JSDOM } from 'jsdom';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
const ROOT_DIR = join(__dirname, '..');

interface ElementLabel {
  selector: string;
  xpath: string;
  keep: boolean;
  autoGenerated: boolean;
}

interface LabeledExample {
  id: string;
  url?: string;
  originalHtml: string;
  cleanedHtml: string;
  labels: ElementLabel[];
}

interface LabeledDataset {
  examples: LabeledExample[];
}

/**
 * Generate XPath for an element.
 */
function getXPath(element: Element): string {
  if (element.id) {
    return `//*[@id="${element.id}"]`;
  }
  
  const parts: string[] = [];
  let current: Element | null = element;
  
  while (current && current.nodeType === 1) {
    let index = 1;
    let sibling = current.previousElementSibling;
    
    while (sibling) {
      if (sibling.tagName === current.tagName) {
        index++;
      }
      sibling = sibling.previousElementSibling;
    }
    
    const tagName = current.tagName.toLowerCase();
    parts.unshift(`${tagName}[${index}]`);
    current = current.parentElement;
  }
  
  return '/' + parts.join('/');
}

/**
 * Generate CSS selector for an element (simplified).
 */
function getSelector(element: Element): string {
  if (element.id) {
    return `#${element.id}`;
  }
  
  if (element.className && typeof element.className === 'string') {
    const classes = element.className.trim().split(/\s+/).filter(Boolean);
    if (classes.length > 0) {
      return `.${classes[0]}`;
    }
  }
  
  return element.tagName.toLowerCase();
}

/**
 * Find matching element in cleaned DOM for an element in original DOM.
 * Uses multiple strategies: ID match, XPath match, text content similarity.
 */
function findMatchingElement(
  originalElement: Element,
  cleanedDoc: Document
): Element | null {
  // Strategy 1: Match by ID
  if (originalElement.id) {
    const match = cleanedDoc.getElementById(originalElement.id);
    if (match) return match;
  }
  
  // Strategy 2: Match by XPath
  const xpath = getXPath(originalElement);
  try {
    const result = cleanedDoc.evaluate(
      xpath,
      cleanedDoc,
      null,
      XPathResult.FIRST_ORDERED_NODE_TYPE,
      null
    );
    if (result.singleNodeValue && result.singleNodeValue.nodeType === 1) {
      return result.singleNodeValue as Element;
    }
  } catch {
    // XPath evaluation failed, continue to next strategy
  }
  
  // Strategy 3: Match by text content similarity
  const originalText = originalElement.textContent?.trim() || '';
  if (originalText.length > 20) {
    // Only try text matching for elements with substantial content
    const allElements = cleanedDoc.querySelectorAll('*');
    let bestMatch: Element | null = null;
    let bestSimilarity = 0;
    
    for (const candidate of Array.from(allElements)) {
      const candidateText = candidate.textContent?.trim() || '';
      if (candidateText.length < originalText.length * 0.5) continue;
      
      // Simple similarity: common words
      const originalWords = new Set(originalText.toLowerCase().split(/\s+/));
      const candidateWords = new Set(candidateText.toLowerCase().split(/\s+/));
      const intersection = new Set([...originalWords].filter(w => candidateWords.has(w)));
      const union = new Set([...originalWords, ...candidateWords]);
      const similarity = union.size > 0 ? intersection.size / union.size : 0;
      
      if (similarity > bestSimilarity && similarity > 0.7) {
        bestSimilarity = similarity;
        bestMatch = candidate;
      }
    }
    
    if (bestMatch) return bestMatch;
  }
  
  return null;
}

/**
 * Generate labels by comparing original and cleaned HTML.
 */
function generateLabels(originalHtml: string, cleanedHtml: string): ElementLabel[] {
  const originalDom = new JSDOM(originalHtml);
  const cleanedDom = new JSDOM(cleanedHtml);
  
  const originalDoc = originalDom.window.document;
  const cleanedDoc = cleanedDom.window.document;
  
  const labels: ElementLabel[] = [];
  const processedElements = new Set<Element>();
  
  // Walk through all elements in original HTML
  const NodeFilter = originalDom.window.NodeFilter;
  const walker = originalDoc.createTreeWalker(
    originalDoc.body || originalDoc.documentElement,
    NodeFilter.SHOW_ELEMENT
  );
  
  while (walker.nextNode()) {
    const element = walker.currentNode as Element;
    
    // Skip if already processed (child of removed element)
    if (processedElements.has(element)) continue;
    
    // Find matching element in cleaned HTML
    const match = findMatchingElement(element, cleanedDoc);
    
    const selector = getSelector(element);
    const xpath = getXPath(element);
    
    if (match) {
      // Element exists in cleaned HTML → keep
      labels.push({
        selector,
        xpath,
        keep: true,
        autoGenerated: true,
      });
    } else {
      // Element doesn't exist in cleaned HTML → remove
      labels.push({
        selector,
        xpath,
        keep: false,
        autoGenerated: true,
      });
      
      // Mark all children as processed (they're removed with parent)
      const childWalker = originalDoc.createTreeWalker(
        element,
        originalDom.window.NodeFilter.SHOW_ELEMENT
      );
      while (childWalker.nextNode()) {
        processedElements.add(childWalker.currentNode as Element);
      }
    }
  }
  
  return labels;
}

/**
 * Load existing labeled dataset or create new one.
 */
function loadDataset(): LabeledDataset {
  const datasetPath = join(ROOT_DIR, 'training-data', 'labeled-examples.json');
  
  if (existsSync(datasetPath)) {
    try {
      const content = readFileSync(datasetPath, 'utf-8');
      return JSON.parse(content) as LabeledDataset;
    } catch {
      // File exists but invalid, create new
    }
  }
  
  return { examples: [] };
}

/**
 * Save labeled dataset.
 */
function saveDataset(dataset: LabeledDataset): void {
  const datasetPath = join(ROOT_DIR, 'training-data', 'labeled-examples.json');
  writeFileSync(datasetPath, JSON.stringify(dataset, null, 2), 'utf-8');
}

/**
 * Main function to generate labels for a single example.
 */
function main(): void {
  const exampleId = process.argv[2];
  
  if (!exampleId) {
    console.error('Usage: npx tsx scripts/generate-labels.ts <example-id>');
    console.error('');
    console.error('Example:');
    console.error('  npx tsx scripts/generate-labels.ts cnet-galaxy-chip');
    console.error('');
    console.error('This will look for:');
    console.error('  - training-data/raw/cnet-galaxy-chip-original.html');
    console.error('  - training-data/raw/cnet-galaxy-chip-cleaned.html');
    process.exit(1);
  }
  
  const originalPath = join(ROOT_DIR, 'training-data', 'raw', `${exampleId}-original.html`);
  const cleanedPath = join(ROOT_DIR, 'training-data', 'raw', `${exampleId}-cleaned.html`);
  
  if (!existsSync(originalPath)) {
    console.error(`❌ Original HTML not found: ${originalPath}`);
    process.exit(1);
  }
  
  if (!existsSync(cleanedPath)) {
    console.error(`❌ Cleaned HTML not found: ${cleanedPath}`);
    process.exit(1);
  }
  
  console.log(`\n📄 Processing: ${exampleId}`);
  console.log(`   Original: ${originalPath}`);
  console.log(`   Cleaned:  ${cleanedPath}\n`);
  
  const originalHtml = readFileSync(originalPath, 'utf-8');
  const cleanedHtml = readFileSync(cleanedPath, 'utf-8');
  
  console.log('🔍 Generating labels...');
  const labels = generateLabels(originalHtml, cleanedHtml);
  
  const keepCount = labels.filter(l => l.keep).length;
  const removeCount = labels.filter(l => !l.keep).length;
  
  console.log(`   ✅ Generated ${labels.length} labels:`);
  console.log(`      Keep: ${keepCount}`);
  console.log(`      Remove: ${removeCount}\n`);
  
  // Load existing dataset
  const dataset = loadDataset();
  
  // Check if example already exists
  const existingIndex = dataset.examples.findIndex(ex => ex.id === exampleId);
  
  const example: LabeledExample = {
    id: exampleId,
    originalHtml,
    cleanedHtml,
    labels,
  };
  
  if (existingIndex >= 0) {
    console.log(`⚠️  Example "${exampleId}" already exists. Replacing...`);
    dataset.examples[existingIndex] = example;
  } else {
    dataset.examples.push(example);
  }
  
  // Save dataset
  saveDataset(dataset);
  
  console.log(`✅ Saved to training-data/labeled-examples.json`);
  console.log(`   Total examples: ${dataset.examples.length}\n`);
}

main();

