#!/usr/bin/env node
/**
 * Train ML model for element cleanup classification.
 * 
 * This script:
 * 1. Loads labeled examples from training-data/labeled-examples.json
 * 2. Extracts features for each labeled element
 * 3. Trains a simple threshold-based classifier (upgradeable to XGBoost later)
 * 4. Saves model to src/extraction/ml/model.json
 * 5. Generates metrics to training-data/metrics.json
 * 
 * Usage: npm run train
 */

import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

import { JSDOM } from 'jsdom';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
const ROOT_DIR = join(__dirname, '..');

// Import feature extraction (we'll need to make it work in Node.js)
import { extractElementFeatures } from '../src/extraction/ml/features';
import type { FeatureVector } from '../src/extraction/ml/types';

interface ElementLabel {
  selector: string;
  xpath: string;
  keep: boolean;
  autoGenerated: boolean;
}

interface LabeledExample {
  id: string;
  url?: string;
  originalHtml: string;
  cleanedHtml: string;
  labels: ElementLabel[];
}

type LabeledDataset = LabeledExample[] | { examples: LabeledExample[] };

interface TrainingExample {
  features: FeatureVector;
  label: number; // 1 for keep, 0 for remove
}

interface SimpleModel {
  type: 'threshold';
  version: string;
  thresholds: {
    [key: string]: {
      keepThreshold: number;
      removeThreshold: number;
    };
  };
  featureWeights: {
    [key: string]: number;
  };
  defaultKeep: boolean;
}

interface TrainingMetrics {
  accuracy: number;
  precision: number;
  recall: number;
  f1: number;
  totalExamples: number;
  keepExamples: number;
  removeExamples: number;
  confusionMatrix: {
    truePositive: number;
    trueNegative: number;
    falsePositive: number;
    falseNegative: number;
  };
}

/**
 * Find element in DOM using selector or xpath.
 */
function findElement(doc: Document, label: ElementLabel): Element | null {
  // Try selector first
  try {
    const element = doc.querySelector(label.selector);
    if (element) return element;
  } catch {
    // Invalid selector, try xpath
  }
  
  // Try xpath
  try {
    const result = doc.evaluate(
      label.xpath,
      doc,
      null,
      XPathResult.FIRST_ORDERED_NODE_TYPE,
      null
    );
    if (result.singleNodeValue && result.singleNodeValue.nodeType === 1) {
      return result.singleNodeValue as Element;
    }
  } catch {
    // XPath failed
  }
  
  return null;
}

/**
 * Extract training examples from labeled dataset.
 */
function extractTrainingExamples(dataset: LabeledDataset): TrainingExample[] {
  const examples: TrainingExample[] = [];
  
  // Handle both array format and object format
  const labeledExamples = Array.isArray(dataset) ? dataset : dataset.examples;
  
  for (const example of labeledExamples) {
    const originalDom = new JSDOM(example.originalHtml);
    const originalDoc = originalDom.window.document;
    
    for (const label of example.labels) {
      const element = findElement(originalDoc, label);
      if (!element) {
        console.warn(`⚠️  Could not find element for label: ${label.selector} (${label.xpath})`);
        continue;
      }
      
      try {
        const features = extractElementFeatures(element);
        examples.push({
          features,
          label: label.keep ? 1 : 0,
        });
      } catch (error) {
        console.warn(`⚠️  Failed to extract features for element: ${label.selector}`, error);
      }
    }
  }
  
  return examples;
}

/**
 * Train a simple threshold-based model.
 * This learns optimal thresholds for each feature.
 */
function trainSimpleModel(examples: TrainingExample[]): SimpleModel {
  if (examples.length === 0) {
    throw new Error('No training examples available');
  }
  
  const keepExamples = examples.filter(e => e.label === 1);
  const removeExamples = examples.filter(e => e.label === 0);
  
  console.log(`\n📊 Training Data:`);
  console.log(`   Total examples: ${examples.length}`);
  console.log(`   Keep examples: ${keepExamples.length}`);
  console.log(`   Remove examples: ${removeExamples.length}`);
  
  if (keepExamples.length === 0 || removeExamples.length === 0) {
    throw new Error('Need both keep and remove examples to train');
  }
  
  // Get feature names
  const featureNames = Object.keys(examples[0].features) as (keyof FeatureVector)[];
  
  // Calculate feature weights based on separation between keep/remove
  const featureWeights: Record<string, number> = {};
  const thresholds: Record<string, { keepThreshold: number; removeThreshold: number }> = {};
  
  for (const featureName of featureNames) {
    const keepValues = keepExamples.map(e => e.features[featureName]);
    const removeValues = removeExamples.map(e => e.features[featureName]);
    
    const keepMean = keepValues.reduce((a, b) => a + b, 0) / keepValues.length;
    const removeMean = removeValues.reduce((a, b) => a + b, 0) / removeValues.length;
    const keepStd = Math.sqrt(
      keepValues.reduce((sum, v) => sum + Math.pow(v - keepMean, 2), 0) / keepValues.length
    );
    const removeStd = Math.sqrt(
      removeValues.reduce((sum, v) => sum + Math.pow(v - removeMean, 2), 0) / removeValues.length
    );
    
    // Weight based on separation (larger separation = more important)
    const separation = Math.abs(keepMean - removeMean);
    const avgStd = (keepStd + removeStd) / 2;
    const weight = avgStd > 0 ? separation / avgStd : 0;
    
    featureWeights[featureName] = weight;
    
    // Set thresholds (mean ± 0.5 std)
    thresholds[featureName] = {
      keepThreshold: keepMean - 0.5 * keepStd,
      removeThreshold: removeMean + 0.5 * removeStd,
    };
  }
  
  // Default: keep if more keep examples than remove
  const defaultKeep = keepExamples.length > removeExamples.length;
  
  return {
    type: 'threshold',
    version: '1.0.0',
    thresholds,
    featureWeights,
    defaultKeep,
  };
}

/**
 * Evaluate model on training examples.
 */
function evaluateModel(
  model: SimpleModel,
  examples: TrainingExample[]
): TrainingMetrics {
  let truePositive = 0;
  let trueNegative = 0;
  let falsePositive = 0;
  let falseNegative = 0;
  
  for (const example of examples) {
    const prediction = predictWithModel(model, example.features);
    const actual = example.label === 1;
    
    if (prediction && actual) truePositive++;
    else if (!prediction && !actual) trueNegative++;
    else if (prediction && !actual) falsePositive++;
    else if (!prediction && actual) falseNegative++;
  }
  
  const accuracy = (truePositive + trueNegative) / examples.length;
  const precision = truePositive + falsePositive > 0 
    ? truePositive / (truePositive + falsePositive) 
    : 0;
  const recall = truePositive + falseNegative > 0
    ? truePositive / (truePositive + falseNegative)
    : 0;
  const f1 = precision + recall > 0
    ? (2 * precision * recall) / (precision + recall)
    : 0;
  
  return {
    accuracy,
    precision,
    recall,
    f1,
    totalExamples: examples.length,
    keepExamples: examples.filter(e => e.label === 1).length,
    removeExamples: examples.filter(e => e.label === 0).length,
    confusionMatrix: {
      truePositive,
      trueNegative,
      falsePositive,
      falseNegative,
    },
  };
}

/**
 * Predict using simple threshold model.
 */
function predictWithModel(model: SimpleModel, features: FeatureVector): boolean {
  let keepScore = 0;
  let removeScore = 0;
  let totalWeight = 0;
  
  for (const [featureName, weight] of Object.entries(model.featureWeights)) {
    const featureValue = features[featureName as keyof FeatureVector] as number;
    const threshold = model.thresholds[featureName];
    
    if (!threshold) continue;
    
    // Score based on distance from thresholds
    const keepDistance = Math.abs(featureValue - threshold.keepThreshold);
    const removeDistance = Math.abs(featureValue - threshold.removeThreshold);
    
    if (keepDistance < removeDistance) {
      keepScore += weight;
    } else {
      removeScore += weight;
    }
    totalWeight += weight;
  }
  
  if (totalWeight === 0) {
    return model.defaultKeep;
  }
  
  return keepScore > removeScore;
}

/**
 * Main training function.
 */
function main(): void {
  console.log('\n🚀 Starting Model Training\n');
  
  const datasetPath = join(ROOT_DIR, 'training-data', 'labeled-examples.json');
  
  if (!existsSync(datasetPath)) {
    console.error('❌ Dataset not found:', datasetPath);
    console.error('   Run generate-labels.ts first to create labeled examples.');
    process.exit(1);
  }
  
  let dataset: LabeledDataset;
  try {
    const content = readFileSync(datasetPath, 'utf-8');
    dataset = JSON.parse(content) as LabeledDataset;
  } catch (error) {
    console.error('❌ Failed to parse dataset:', error);
    process.exit(1);
  }
  
  // Handle both array format and object format
  const examples = Array.isArray(dataset) ? dataset : dataset.examples;
  
  if (!examples || examples.length === 0) {
    console.error('❌ No examples found in dataset');
    process.exit(1);
  }
  
  console.log(`📦 Loading ${examples.length} labeled examples...`);
  
  // Extract training examples
  console.log('🔍 Extracting features from labeled elements...');
  const trainingExamples = extractTrainingExamples({ examples });
  
  if (trainingExamples.length === 0) {
    console.error('❌ No valid training examples extracted');
    process.exit(1);
  }
  
  console.log(`✅ Extracted ${trainingExamples.length} training examples\n`);
  
  // Train model
  console.log('🎓 Training model...');
  const model = trainSimpleModel(trainingExamples);
  
  // Evaluate
  console.log('\n📈 Evaluating model...');
  const metrics = evaluateModel(model, trainingExamples);
  
  console.log('\n📊 Training Metrics:');
  console.log(`   Accuracy: ${(metrics.accuracy * 100).toFixed(1)}%`);
  console.log(`   Precision: ${(metrics.precision * 100).toFixed(1)}%`);
  console.log(`   Recall: ${(metrics.recall * 100).toFixed(1)}%`);
  console.log(`   F1 Score: ${(metrics.f1 * 100).toFixed(1)}%`);
  console.log('\n   Confusion Matrix:');
  console.log(`     True Positives: ${metrics.confusionMatrix.truePositive}`);
  console.log(`     True Negatives: ${metrics.confusionMatrix.trueNegative}`);
  console.log(`     False Positives: ${metrics.confusionMatrix.falsePositive}`);
  console.log(`     False Negatives: ${metrics.confusionMatrix.falseNegative}`);
  
  // Save model
  const modelPath = join(ROOT_DIR, 'src', 'extraction', 'ml', 'model.json');
  writeFileSync(modelPath, JSON.stringify(model, null, 2), 'utf-8');
  console.log(`\n✅ Model saved to: ${modelPath}`);
  
  // Save metrics
  const metricsPath = join(ROOT_DIR, 'training-data', 'metrics.json');
  writeFileSync(metricsPath, JSON.stringify(metrics, null, 2), 'utf-8');
  console.log(`✅ Metrics saved to: ${metricsPath}\n`);
  
  // Warnings
  if (examples.length < 10) {
    console.log('⚠️  Warning: Very few training examples (<10)');
    console.log('   Model may not generalize well. Consider adding more examples.\n');
  }
  
  if (metrics.accuracy < 0.7) {
    console.log('⚠️  Warning: Low accuracy (<70%)');
    console.log('   Model may need more training data or feature engineering.\n');
  }
}

main();

