#!/usr/bin/env node
/**
 * Validate training data format and quality.
 * 
 * Usage: npx tsx scripts/validate-training-data.ts
 */

import { readFileSync, existsSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
const ROOT_DIR = join(__dirname, '..');

interface ElementLabel {
  selector: string;
  xpath: string;
  keep: boolean;
  autoGenerated: boolean;
}

interface LabeledExample {
  id: string;
  url?: string;
  originalHtml: string;
  cleanedHtml: string;
  labels: ElementLabel[];
}

interface LabeledDataset {
  examples: LabeledExample[];
}

function validateDataset(): void {
  const datasetPath = join(ROOT_DIR, 'training-data', 'labeled-examples.json');
  
  if (!existsSync(datasetPath)) {
    console.error('❌ Dataset not found:', datasetPath);
    console.error('   Run generate-labels.ts first to create labeled examples.');
    process.exit(1);
  }
  
  let dataset: LabeledDataset;
  try {
    const content = readFileSync(datasetPath, 'utf-8');
    dataset = JSON.parse(content) as LabeledDataset;
  } catch (error) {
    console.error('❌ Failed to parse dataset:', error);
    process.exit(1);
  }
  
  console.log('\n📊 VALIDATION REPORT');
  console.log('='.repeat(60));
  
  if (!dataset.examples || !Array.isArray(dataset.examples)) {
    console.error('❌ Invalid dataset format: missing examples array');
    process.exit(1);
  }
  
  const totalExamples = dataset.examples.length;
  console.log(`\n📦 Total Examples: ${totalExamples}`);
  
  if (totalExamples === 0) {
    console.log('⚠️  No examples found. Add examples using generate-labels.ts');
    return;
  }
  
  let totalLabels = 0;
  let totalKeep = 0;
  let totalRemove = 0;
  const issues: string[] = [];
  
  dataset.examples.forEach((example, index) => {
    // Validate example structure
    if (!example.id) {
      issues.push(`Example ${index}: missing id`);
    }
    if (!example.originalHtml) {
      issues.push(`Example ${example.id || index}: missing originalHtml`);
    }
    if (!example.cleanedHtml) {
      issues.push(`Example ${example.id || index}: missing cleanedHtml`);
    }
    if (!example.labels || !Array.isArray(example.labels)) {
      issues.push(`Example ${example.id || index}: missing or invalid labels array`);
      return;
    }
    
    const keepCount = example.labels.filter(l => l.keep).length;
    const removeCount = example.labels.filter(l => !l.keep).length;
    
    totalLabels += example.labels.length;
    totalKeep += keepCount;
    totalRemove += removeCount;
    
    // Check label distribution
    if (example.labels.length === 0) {
      issues.push(`Example ${example.id}: no labels`);
    }
    if (keepCount === 0) {
      issues.push(`Example ${example.id}: no "keep" labels`);
    }
    if (removeCount === 0) {
      issues.push(`Example ${example.id}: no "remove" labels`);
    }
  });
  
  // Summary statistics
  console.log(`\n📈 Label Statistics:`);
  console.log(`   Total labels: ${totalLabels}`);
  console.log(`   Keep labels: ${totalKeep} (${((totalKeep / totalLabels) * 100).toFixed(1)}%)`);
  console.log(`   Remove labels: ${totalRemove} (${((totalRemove / totalLabels) * 100).toFixed(1)}%)`);
  console.log(`   Average labels per example: ${(totalLabels / totalExamples).toFixed(1)}`);
  
  // Issues
  if (issues.length > 0) {
    console.log(`\n⚠️  Issues Found (${issues.length}):`);
    issues.forEach(issue => console.log(`   - ${issue}`));
  } else {
    console.log(`\n✅ No issues found!`);
  }
  
  // Recommendations
  console.log(`\n💡 Recommendations:`);
  if (totalExamples < 50) {
    console.log(`   - Add more examples (currently ${totalExamples}, target: 50+)`);
  }
  if (totalRemove / totalLabels < 0.1) {
    console.log(`   - Low "remove" ratio (${((totalRemove / totalLabels) * 100).toFixed(1)}%). Ensure examples include noise elements.`);
  }
  if (totalRemove / totalLabels > 0.5) {
    console.log(`   - High "remove" ratio (${((totalRemove / totalLabels) * 100).toFixed(1)}%). Verify examples are correct.`);
  }
  
  console.log('\n' + '='.repeat(60) + '\n');
  
  process.exit(issues.length > 0 ? 1 : 0);
}

validateDataset();


